### PR TITLE
Fix for fields that you want to resolve without arguments

### PR DESCRIPTION
**Pull request by matthewmueller**
Hey awesome library! Saves a ton of keystrokes. Noticed there's a bug with resolves. 

Right now you cannot resolve fields that aren't functions. This is supported in the regular graphql library, but resolves get ignored here. This PR fixes this.

``` js
var q = createQuery(`
  type Company {
    ticker: String!
    name: String
    short_name: String
    summary: Financials
  }

  type Query {
    company(ticker: String!): Company
  }
`, {
  Company: {
    short_name (company) {
      return company.short_name.replace('.Inc', '')
    }
  },
  Query: {
    company (root, args) {
      return Company_Model.findOne({ ticker: args.ticker })
    }
  }
})
```

Let me know if there's anything else you'd like me to do.

### CODE REVIEW

**Comment by matthewmueller** [comment]
Additionally, added support for reserved words to be fields:

```
type Fruit {
   type: String
}
```

was blowing up

**Comment by ForbesLindesay** [comment]
It should already support resolving fields that don't take args, just use `()` to specify empty arguments and it will be treated as computed.

**Comment by matthewmueller** [comment]
Ah okay, false alarm. Thoughts on the 2nd part (added support for reserved words to be fields)? I can reopen with a more concise PR if that's preferred.

**Comment by violet-day** [comment]
+1

**Comment by matthewmueller** [comment]
_(Going through old PRs and closing them)_

**Pull request closed without merging**
